name: API FOR Deploymentt

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |              
       #curl -i -u mangeshpa:$Token https://api.github.com/KalpanaAddagada/Javawar/deployments
            #-d “{“visibility”:“private”}”
       curl -H "Authorization:$Token" \https://api.github.com/KalpanaAddagada/Javawar/deployments?q=user:mangespa
       #curl -i -u mangeshpa:$Token https://api.github.com/KalpanaAddagada/Javawar/deployments&Token=$Token
       #curl -H “Authorization: token Token” https://api.github.com/KalpanaAddagada/Javawar/deployments?q=user:mangespa
