name: API FOR PULL REQUEST  

on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: windows-2019
    steps:

    #- name: API FOR PULL REQUEST 
      #run: |
       #curl https://api.github.com/repos/mangeshpa/JestReport/pulls?state=all | jq '.[] | {CreatedBy: .user.login, SourceBranch: .head.ref, DestinationBranch: .base.ref, Pull_Request_Number: .number, Repository: .url, Creation_Date: .created_at, Pull_Request_Status: .state, Reviewers: .requested_reviewers[].login, Approvers: .assignee.login}' #>> "./Pullrequests.json"

       - name: checkout code
         uses: actions/checkout@v2
         
       - name: Read branch.properties
         id: version
         uses: juliangruber/read-file-action@v1
         with:
           path: ./build/version.properties

       - name: Assign release version from version.properties to Env variable
         run: |
            echo "${{ steps.host }}" >> $GITHUB_ENV          
          
       - name: Echo release version from  Env variable
         run: |
            echo "${{ env.release_version }}"
       
       
