name: API FOR PULL REQUEST

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: API FOR PULL REQUEST
      run: |
       curl https://api.github.com/repos/miteshNeema/MavenDemo/pulls?state=open | jq '.[] | {CreatedBy: .user.login, SourceBranch: .head.ref, DestinationBranch: .base.ref, Pull_Request_Number: .number, Repository: .url, Creation_Date: .created_at, Pull_Request_Status: .state, Reviewers: .requested_reviewers, Approvers: .assignees}' >> "./output.json"
       
       echo "TAG_NAME=$(curl \
       -H "Accept: application/vnd.github.v3+json" \
       https://api.github.com/repos/mangeshpa/HelloWorldDotNet/stats/participation | jq '.["all"] | add')" 
       echo "$TAG_NAME"
                     
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
