name: API FOR PULL REQUEST

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: API FOR PULL REQUEST
      run: |
       #curl https://api.github.com/repos/mangeshpa/JestReport/pulls | jq '.[] | {CreatedBy: .user.login, SourceBranch: .head.ref, DestinationBranch: .base.ref, Pull_Request_Number: .number, Repository: .url, Creation_Date: .created_at, Pull_Request_Status: .state, Reviewers: .requested_reviewers[].login, Approvers: .assignee.login}' >> "./output.json"
       #sed  -i '1i [' ./output.json
       #sed 's/}/},/g' ./output.json >> "./outputFinal.json"
       #sed '$ s/.$//' ./outputFinal.json >> "./outputFinal2.json"
       #sed -i '$ a\'"]" ./outputFinal2.json

    - name: API FOR PULL REQUEST
      run: |
       curl https://api.github.com/repos/mangeshpa/JestReport/pulls | jq '.[] | {CreatedBy: .user.login, SourceBranch: .head.ref, DestinationBranch: .base.ref, Pull_Request_Number: .number, Repository: .url, Creation_Date: .created_at, Pull_Request_Status: .state, Reviewers: .requested_reviewers[].login, Approvers: .assignee.login}' >> "./Pullrequests.json"
       sed  -i '1i [' ./Pullrequests.json
       sed 's/}/},/g' ./Pullrequests.json >> "./PullrequestsFinal.json"
       sed '$ s/.$//' ./PullrequestsFinal.json >> "./Pullrequests_Final.json"
       sed -i '$ a\'"]" ./Pullrequests_Final.json

    - name: Upload a Test Artifact for Pull Request
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./Pullrequests_Final.json
        
                     
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./outputFinal2.json
